scan:
  # Root directory to scan (Make sure this is correctly mapped in WSL)
  scan_root: "/mnt/c/Users/"

  # File types to include in the scan
  include_patterns:
    - "*.py"     # Python scripts
    - "*.js"     # JavaScript files
    - "*.json"   # JSON configuration/data files
    - "*.cfg"    # General configuration files
    - "*.ini"    # INI configuration files
    - "*.yml"    # YAML configuration files

  # Directories to exclude from scanning
  exclude_directories:
    - ".git"          # Git repositories
    - "node_modules"  # Node.js dependencies
    - "/proc"         # Linux system processes (avoid scanning system directories)
    - "/sys"          # Linux system files
    - "C:\\Windows"   # Windows system directory (excluded for safety)

  # Scan settings
  dry_run: false       # If true, only lists files without scanning them
  verbose: true        # Enable detailed output while scanning
  anonymize: false     # If true, hides full file paths in the final report
